### ISSUE TITLE
Change Foreground/Background Color, add logo to center

### ISSUE THREAD

**Issue by tvajjhala** [promops/flutter_pretty_qr#1]
Hi,
Thank you so much for this plugin. I have been looking for something like this for a while. Is it possible to change the foreground and background color of the rounded QR code and to also add a logo in the center? Something like seen https://raw.githubusercontent.com/kozakdenys/qr-code-styling/master/app/assets/instagram_example.png and https://raw.githubusercontent.com/kozakdenys/qr-code-styling/master/app/assets/facebook_example.png

I appreciate the help. Thank you again!

**Comment by promops** [comment]
Hi, i will do it soon
