### ISSUE TITLE
Lag with larger pieces of data

### ISSUE THREAD

**Issue by Andrewcpu** [promops/flutter_pretty_qr#10]
Hi there!

I'm experiencing severe lag when displaying a QR code with >200 characters stored as data. It's not dynamic data, so it shouldn't have to be redrawn every frame, is there a way that you would be able to fix this? Can you recommend something if not?

**Comment by promops** [comment]
@AndrewCPU 
Hi, i'll try to see what's the problem. So far you can see here
https://api.flutter.dev/flutter/widgets/RepaintBoundary-class.html

**Comment by AndrewCPU** [comment]
HI @promops, I was able to significantly reduce lag by changing the rounded corners flag from true to false. But ideally, we could use rounded corners without lag, though I know the math behind rounding them is intensive.

**Comment by promops** [comment]
@AndrewCPU  Hi, can you provide the code to reproduce?

**Comment by BraveEvidence** [comment]
This might help https://www.youtube.com/watch?v=9ADSWmPCJMg&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=6 https://www.youtube.com/watch?v=ZRUE1i15TYw&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=7
