### ISSUE TITLE
Upload version 2.0.3 on pub.dev

### ISSUE THREAD

**Issue by sstasi95** [promops/flutter_pretty_qr#12]
Hi,

On pub.dev there is still the old 2.0.2 version. Could you please upload the new version? The reason is that version 2.0.2 requires version ^2.0.0 of qr package, which is making version resolution difficult in some cases.

Thanks,

Simone

**Comment by promops** [comment]
@sstasi95 Hi! 
https://pub.dev/packages/pretty_qr_code/versions/2.0.3
