### ISSUE TITLE
How to save QR code?

### ISSUE THREAD

**Issue by minhdanh** [promops/flutter_pretty_qr#14]
Hello, how can I save the QR code with this package? Is that possible?
Thanks!

**Comment by kyleorin** [comment]
You can use other packages to convert the widget into an image and save it like that; don't think it's necessary for a package like this.

**Comment by wojide0301** [comment]
When will version 3.0.1 be released?

**Comment by promops** [comment]
@wojide0301 Hi! Sorry for delay
https://pub.dev/packages/pretty_qr_code/versions/3.1.0
