### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by Mae623** [promops/flutter_pretty_qr#15]
`======== Exception caught by image resource service ================================================
The following StateError was thrown by a synchronously-called image error listener:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
1      _PrettyQrState._loadImage.<anonymous closure> (package:pretty_qr_code/src/pretty_qr.dart:57:17)
2      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:535:26)
3      MultiImageStreamCompleter.addListener (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:171:11)
4      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:376:26)
5      _PrettyQrState._loadImage (package:pretty_qr_code/src/pretty_qr.dart:54:12)
6      _PrettyQrState.build (package:pretty_qr_code/src/pretty_qr.dart:75:21)
7      StatefulElement.build (package:flutter/src/widgets/framework.dart:5064:27)
8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4952:15)
9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5117:11)
10     Element.rebuild (package:flutter/src/widgets/framework.dart:4672:7)
11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4934:5)
12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5108:11)
13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4928:5)
...     Normal element mounting (13 frames)
26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3940:16)
27     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6490:36)
28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6502:32)
29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3940:16)
30     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6490:36)
31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6502:32)
32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3940:16)
33     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6490:36)
34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6502:32)
...     Normal element mounting (112 frames)
146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3940:16)
147    Element.updateChild (package:flutter/src/widgets/framework.dart:3677:18)
148    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135:18)
149    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2689:19)
150    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
151    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2291:59)
152    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1050:15)
153    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2291:14)
154    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
155    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:313:5)
156    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
157    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
158    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
159    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1060:7)
160    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
161    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
162    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
163    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
164    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
165    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
166    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
167    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
168    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
169    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
170    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
171    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
172    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
173    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
174    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
175    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
176    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
177    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
178    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
179    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
180    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
181    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:585:43)
182    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:612:12)
183    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
184    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
185    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
186    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
187    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
188    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
189    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
190    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
191    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
192    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
193    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
194    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
195    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
196    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
197    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
198    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
199    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
200    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:14)
201    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
202    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
203    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
204    RenderObject.layout (package:flutter/src/rendering/object.dart:2180:7)
205    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
206    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:843:15)
207    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2019:7)
208    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1014:18)
209    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:512:19)
210    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:13)
211    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
212    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1286:15)
213    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1216:9)
214    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1074:5)
215    _invoke (dart:ui/hooks.dart:142:13)
216    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:368:5)
217    _drawFrame (dart:ui/hooks.dart:112:31)
(elided one frame from dart:async)
====================================================================================================`

**Comment by Mae623** [comment]
flutter doctor

[✓] Flutter (Channel master, 3.8.0-14.0.pre.6, on macOS 13.3.1 22E772610a darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)

**Comment by promops** [comment]
Fixed in v3.0.0
