### ISSUE TITLE
Qr not working with center image

### ISSUE THREAD

**Issue by gmhz** [promops/flutter_pretty_qr#22]
```
 SizedBox(
              height: context.height * 0.2956,
              child: PrettyQrView.data(
                data: 'https://www.google.com/',
                decoration: const PrettyQrDecoration(
                  shape: PrettyQrRoundedSymbol(
                    color: Color(0xFF8C8C8C),
                  ),
                  image: PrettyQrDecorationImage(
                    image: AssetImage('assets/icons/branches.png'),
                    // scale: .3
                    // height: context.height * 0.2956 * .3636,
                  ),
                ),
              ),
            )
```

<img width="224" alt="Screenshot 2023-09-24 at 16 10 39" src="https://github.com/promops/flutter_pretty_qr/assets/18304266/5c76afe5-b35f-4b6f-be7f-e550ea49ae3f">

But without an image at the center, it's working
<img width="224" alt="Screenshot 2023-09-24 at 16 12 29" src="https://github.com/promops/flutter_pretty_qr/assets/18304266/d583ee41-8f35-4d57-a896-ac692b5cb537">

```
SizedBox(
              height: context.height * 0.2956,
              child: PrettyQrView.data(
                data: 'https://www.google.com/',
                decoration: const PrettyQrDecoration(
                  shape: PrettyQrRoundedSymbol(
                    color: Color(0xFF8C8C8C),
                  ),
                  // image: PrettyQrDecorationImage(
                  //   image: AssetImage('assets/icons/branches.png'),
                  //   // scale: .3
                  //   // height: context.height * 0.2956 * .3636,
                  // ),
                ),
              ),
),
```

As I noticed adding center image removes some data (dots the center).
Seems like this is the cause.
Sorry, I have no idea how qr are generated, maybe there's a solution with rearranging the dots of qr, so image can be actually placed?

**Comment by promops** [comment]
@gmhz Hi!
yes, it's true, data has a loss limit, in this case I can only advise you to change ErrorCorrectionLevel or Version in manual mode (**PrettyQrView** instead of **PrettyQrView.data**).
In future versions I will add a check for acceptable data loss

**Comment by gmhz** [comment]
> @gmhz Hi! yes, it's true, data has a loss limit, in this case I can only advise you to change ErrorCorrectionLevel (in **PrettyQrView.data**) or Version in manual mode (**PrettyQrView** instead of **PrettyQrView.data**).If you use image with qr, i advice to set ErrorCorrectionLevel to H always In future versions I will add a check for acceptable data loss

Thanks for your answer. Yes later I found out the ErrorCorrectionLevel and by increasing it fixed the issue.
