### ISSUE TITLE
How to set rounded corners QR code？

### ISSUE THREAD

**Issue by BodenTide** [promops/flutter_pretty_qr#27]
`PrettyQrView.data(
                                data: 'https://www.google.ru',
                                errorCorrectLevel: QrErrorCorrectLevel.M,
                                decoration: PrettyQrDecoration(
                                  shape: PrettyQrSmoothSymbol(
                                    color: thirdTextColor,
                                    **roundFactor: 0.5**
                                  )
                                ),
                              )`

Even if I set roundFactor, it doesn't work. How should I set the rounded corners of the QR code? I need help!

**Comment by nxtSwitch** [comment]
Hi @BodenTide 👋
Thanks for opening an issue!

Can you please provide some more context on what shape of QR code you want or a sample image?

**Comment by BodenTide** [comment]
Sorry, I misunderstood the requirements. This problem should be a container encoding problem

**Comment by BodenTide** [comment]
If I want the following QR code to look like, how should I set the parameters? The QR code will have some rounded corners around it.

<img width="504" alt="WeChat9e26bb6c26c14d31a0d08c06d012d20d" src="https://github.com/promops/flutter_pretty_qr/assets/137751112/4f13f180-90c2-4c79-ba2a-ea17cf3bd1ba">

**Comment by nxtSwitch** [comment]
In this case, you need to wrap `PrettyQrView` with `ClipRRect` widget:

```dart
ClipRRect(
  borderRadius: BorderRadius.circular(16), // rounded corners
  child: PrettyQrView.data(
    data: 'https://www.google.ru',
    errorCorrectLevel: QrErrorCorrectLevel.M,
  ),
)
```

Although it's possible, it's recommended to round corners of the QR code only slightly because it will affect the Finder Pattern, which is intended to assist in an easy location for QR code position, size, and inclination. 

Hope that helps!

**Comment by BodenTide** [comment]
Excellent, this can be achieved, thank you🙏
