### ISSUE TITLE
white stripes

### ISSUE THREAD

**Issue by m0d11** [promops/flutter_pretty_qr#3]
There are small white stripes among pixels on qrcode. Could you please remove it?

<img src="https://user-images.githubusercontent.com/25778578/82243925-10b23c00-9949-11ea-8084-a6ba795a85a4.jpg" width="300">

<img src="https://user-images.githubusercontent.com/25778578/82245575-d8602d00-994b-11ea-98cf-7bcc150ed51c.jpg">

**Comment by promops** [comment]
WIP

**Comment by flakerimi** [comment]
Can you make Color option too?

**Comment by vanlooverenkoen** [comment]
Any progress on this?

**Comment by dJani97** [comment]
this is still an issue with any color
![image](https://user-images.githubusercontent.com/22769564/193458978-5b2f6fd3-7d16-4ee7-a512-03b9d625ed09.png)

**Comment by BraveEvidence** [comment]
This might help https://www.youtube.com/watch?v=9ADSWmPCJMg&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=6 https://www.youtube.com/watch?v=ZRUE1i15TYw&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=7

**Comment by promops** [comment]
Fixed in v3.0.0
