### ISSUE TITLE
Decoration Image not exported in Web

### ISSUE THREAD

**Issue by NOTtheKRish** [promops/flutter_pretty_qr#30]
exportAsImage() **works fine at Android**... but I face **issue in Web**, QR gets generated and stored as image without the Decoration Image (I provided my App logo in PNG format)...
This is the generated output...
![carter_store_qr](https://github.com/promops/flutter_pretty_qr/assets/68280259/bbcd5504-7e9c-4ef5-a473-def2d65937de)

**Comment by promops** [comment]
@NOTtheKRish Hello, thank you for issue. Which Flutter version do you have in your project? Nested images on web should not work until stable 3.7.0.
https://github.com/flutter/flutter/issues/103803

**Comment by NOTtheKRish** [comment]
@promops I'm using Flutter version 3.16.0(stable)

**Comment by promops** [comment]
It look like a problem with html render, try to enable canvaskit render by default

**Comment by NOTtheKRish** [comment]
It's working when I set **renderer** as **canvaskit** at **index.html** file...
Thanks!
