### ISSUE TITLE
The embedded logo causes the QR to be damaged

### ISSUE THREAD

**Issue by vanvixi** [promops/flutter_pretty_qr#43]
<table>
    <tr>
         <th style="text-align: center">Normal</th>
         <th style="text-align: center">-----</th>
         <th style="text-align: center">With logo embedded </th>
    </tr>
    <tr>
    <td> <img src="https://github.com/promops/flutter_pretty_qr/assets/75975945/41fd5da1-7238-4965-b339-c18ea6ee2b48" alt="1" width = 360px height = 360px ></td>
    <td>      </td>
    <td><img src="https://github.com/promops/flutter_pretty_qr/assets/75975945/98b38c47-9141-4a9b-88c8-b67ca7609e10" alt="2" width = 360px height = 360px></td>
    </tr> 
</table>

**Comment by promops** [comment]
@vanvixi Hello, yes, it is not possible to insert picture without code corruption.I advise you to increase the QrErrorCorrectLevel so that your codes are readable

**Comment by vanvixi** [comment]
@promops 
Do you have any suggestions for QrErrorCorrectLevel?
How much do I have to increase it to ensure there are no errors?

**Comment by promops** [comment]
@vanvixi You can see this issue - https://github.com/promops/flutter_pretty_qr/issues/22
in the case of an image, I recommend always putting QrErrorCorrectLevel.H. There are some ideas on how to implement a data loss check, but it is not clear yet

**Comment by vanvixi** [comment]
@promops 
Thank you,
When I increase `QrErrorCorregLevel` to `H` level, I feel there is a delay when pushing to QRCodePage.
I downgraded to `M` qr code still works fine and the lag is gone

**Comment by bschmalb** [comment]
I don't think this issue is closed as the increasing of the error correction level is just a workaround and the QR code should generate with leaving the space in the middle for the image right?

**Comment by nxtSwitch** [comment]
Hi @bschmalb 👋

Unfortunately, the QR code standard does not generally imply inserting anything inside the symbol. Therefore, adding images inside is essentially a life hack over the error correction level.
