### ISSUE TITLE
Android Qr code generation error

### ISSUE THREAD

**Issue by Robert-Stackflow** [promops/flutter_pretty_qr#50]
Hello, I encountered this problem when trying to generate a QR code on Android. It behaves normally on Windows. Is it because the length of my data content is too large?

![1725605749767](https://github.com/user-attachments/assets/137a9900-9257-466d-8524-c5b10a8cb631)

**Comment by promops** [comment]
@Robert-Stackflow  Hi, can you show code example?

**Comment by Robert-Stackflow** [comment]
I have resolved this issue because of the instability of Flutter Alpha.Thank you.
