### ISSUE TITLE
Null safety support?

### ISSUE THREAD

**Issue by jasonlaw** [promops/flutter_pretty_qr#6]
Is there any plan to support for null safety?

**Comment by jasonlaw** [comment]
Thanks, really appreciate it!

**Comment by flakerimi** [comment]
Any news on this?

**Comment by promops** [comment]
@flakerimi  I will start refactoring with null safety support  roughly after April 9

**Comment by asterd** [comment]
Hi.. any update on this?

**Comment by promops** [comment]
https://pub.dev/packages/pretty_qr_code/versions/2.0.0
